/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.sql.Date;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chems
 */
public class BDDAdminCeQuiVeut2 extends javax.swing.JFrame {
    private static boolean val = true;
    private boolean bool = true ;
    private boolean val1 = true ;
    private boolean val2 = true;
    /**
     * Creates new form BDDAdminCeQuiVeut2
     */
    public BDDAdminCeQuiVeut2() {
        
        initComponents();
        
        ajoute_Etudiant.setVisible(false);
        ajoute_EtudiantU2.setVisible(false);
        enseignant4.setVisible(false);
        ajoute_Enseignant1.setVisible(false);
        enseignant3.setVisible(false);
        jPanel1.setVisible(false);
        ajoute_Enseignant.setVisible(false);
        enseignant2.setVisible(false);       
        
        try {
            affiche();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(BDDAdminCeQuiVeut2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jMenu1 = new javax.swing.JMenu();
        jDialog4 = new javax.swing.JDialog();
        jDialog5 = new javax.swing.JDialog();
        jDialog6 = new javax.swing.JDialog();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Choisir = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        AjouteEtudiant = new javax.swing.JButton();
        supprimerEtudiant = new javax.swing.JButton();
        MatriculeEtudiant1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ajoute_Etudiant = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MatriculeEtudiant = new javax.swing.JTextField();
        nomEtudiant = new javax.swing.JTextField();
        prenomEtudiant = new javax.swing.JTextField();
        dateDeNaissanceEtudiant = new com.toedter.calendar.JDateChooser();
        adresseEtudiant = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        enseignant2 = new javax.swing.JPanel();
        AjouteEtudiant2 = new javax.swing.JButton();
        supprimerEtudiant2 = new javax.swing.JButton();
        MatriculeEnseignant4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableEnseignant = new javax.swing.JTable();
        ajoute_Enseignant = new javax.swing.JPanel();
        ajouterEnseignant = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        MatriculeEnseignant6 = new javax.swing.JTextField();
        nomEnseignant6 = new javax.swing.JTextField();
        prenomEnseignant6 = new javax.swing.JTextField();
        ajoute_Enseignant1 = new javax.swing.JPanel();
        ajouterEnseignant1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        MatriculeEnseignant7 = new javax.swing.JTextField();
        nomEnseignant7 = new javax.swing.JTextField();
        prenomEnseignant7 = new javax.swing.JTextField();
        nomEnseignant8 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        enseignant3 = new javax.swing.JPanel();
        AjouteEtudiant3 = new javax.swing.JButton();
        supprimerEtudiant3 = new javax.swing.JButton();
        MatriculeEnseignant5 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableEnseignant1 = new javax.swing.JTable();
        enseignant4 = new javax.swing.JPanel();
        AjouteEtudiant4 = new javax.swing.JButton();
        supprimerEtudiant4 = new javax.swing.JButton();
        MatriculeEnseignant8 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        tableEnseignant2 = new javax.swing.JTable();
        ajoute_EtudiantU2 = new javax.swing.JPanel();
        ajouterEtuUni = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        MatriculeEtudiantU = new javax.swing.JTextField();
        CodeUniteE = new javax.swing.JTextField();
        CC = new javax.swing.JTextField();
        EX = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        TP = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog5Layout = new javax.swing.GroupLayout(jDialog5.getContentPane());
        jDialog5.getContentPane().setLayout(jDialog5Layout);
        jDialog5Layout.setHorizontalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog5Layout.setVerticalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog6Layout = new javax.swing.GroupLayout(jDialog6.getContentPane());
        jDialog6.getContentPane().setLayout(jDialog6Layout);
        jDialog6Layout.setHorizontalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog6Layout.setVerticalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BDDAdmin");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        Choisir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir", "Etudiant", "Enseignant", "Unite", "EtudiantUnite" }));
        Choisir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoisirActionPerformed(evt);
            }
        });
        jPanel6.add(Choisir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        AjouteEtudiant.setText("Ajoute Etudiant");
        AjouteEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouteEtudiantActionPerformed(evt);
            }
        });

        supprimerEtudiant.setText("Suprimer Etudiant");
        supprimerEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerEtudiantActionPerformed(evt);
            }
        });

        jButton3.setText("reduire");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matricule", "Nom", "Prenom", "Date De Naissance", "Adresse"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AjouteEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(supprimerEtudiant)
                        .addGap(18, 18, 18)
                        .addComponent(MatriculeEtudiant1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjouteEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supprimerEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatriculeEtudiant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Matricule");

        jLabel3.setText("Nom");

        jLabel4.setText("Prénom");

        jLabel5.setText("Date de Naissance");

        prenomEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomEtudiantActionPerformed(evt);
            }
        });

        adresseEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresseEtudiantActionPerformed(evt);
            }
        });

        jLabel6.setText("Adresse");

        javax.swing.GroupLayout ajoute_EtudiantLayout = new javax.swing.GroupLayout(ajoute_Etudiant);
        ajoute_Etudiant.setLayout(ajoute_EtudiantLayout);
        ajoute_EtudiantLayout.setHorizontalGroup(
            ajoute_EtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajoute_EtudiantLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adresseEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(ajoute_EtudiantLayout.createSequentialGroup()
                .addGroup(ajoute_EtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoute_EtudiantLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(ajoute_EtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ajoute_EtudiantLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateDeNaissanceEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ajoute_EtudiantLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MatriculeEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prenomEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ajoute_EtudiantLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ajoute_EtudiantLayout.setVerticalGroup(
            ajoute_EtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoute_EtudiantLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(ajoute_EtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoute_EtudiantLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(ajoute_EtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MatriculeEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(nomEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(prenomEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(ajoute_EtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoute_EtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dateDeNaissanceEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajoute_EtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adresseEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        AjouteEtudiant2.setText("Ajoute Enseignant");
        AjouteEtudiant2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouteEtudiant2ActionPerformed(evt);
            }
        });

        supprimerEtudiant2.setText("Suprimer Enseignant");
        supprimerEtudiant2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerEtudiant2ActionPerformed(evt);
            }
        });

        jButton5.setText("reduire");

        tableEnseignant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Matricule", "Nom", "Prenom"
            }
        ));
        jScrollPane6.setViewportView(tableEnseignant);

        jScrollPane5.setViewportView(jScrollPane6);

        javax.swing.GroupLayout enseignant2Layout = new javax.swing.GroupLayout(enseignant2);
        enseignant2.setLayout(enseignant2Layout);
        enseignant2Layout.setHorizontalGroup(
            enseignant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enseignant2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enseignant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(enseignant2Layout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enseignant2Layout.createSequentialGroup()
                        .addComponent(AjouteEtudiant2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(supprimerEtudiant2)
                        .addGap(18, 18, 18)
                        .addComponent(MatriculeEnseignant4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addGap(33, 33, 33))
        );
        enseignant2Layout.setVerticalGroup(
            enseignant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enseignant2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enseignant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjouteEtudiant2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supprimerEtudiant2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatriculeEnseignant4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        ajouterEnseignant.setBackground(new java.awt.Color(0, 153, 0));
        ajouterEnseignant.setForeground(new java.awt.Color(255, 255, 255));
        ajouterEnseignant.setText("Ajouter");
        ajouterEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterEnseignantActionPerformed(evt);
            }
        });

        jLabel13.setText("Matricule");

        jLabel14.setText("Nom");

        jLabel15.setText("Prénom");

        MatriculeEnseignant6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculeEnseignant6ActionPerformed(evt);
            }
        });

        prenomEnseignant6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomEnseignant6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajoute_EnseignantLayout = new javax.swing.GroupLayout(ajoute_Enseignant);
        ajoute_Enseignant.setLayout(ajoute_EnseignantLayout);
        ajoute_EnseignantLayout.setHorizontalGroup(
            ajoute_EnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoute_EnseignantLayout.createSequentialGroup()
                .addGroup(ajoute_EnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoute_EnseignantLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MatriculeEnseignant6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomEnseignant6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prenomEnseignant6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajoute_EnseignantLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(ajouterEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ajoute_EnseignantLayout.setVerticalGroup(
            ajoute_EnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoute_EnseignantLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(ajoute_EnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoute_EnseignantLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13))
                    .addGroup(ajoute_EnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MatriculeEnseignant6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(nomEnseignant6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(prenomEnseignant6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ajouterEnseignant)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ajouterEnseignant1.setBackground(new java.awt.Color(0, 153, 0));
        ajouterEnseignant1.setForeground(new java.awt.Color(255, 255, 255));
        ajouterEnseignant1.setText("Ajouter");
        ajouterEnseignant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterEnseignant1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Code Unite");

        jLabel17.setText("Libelle");

        jLabel18.setText("Nombre d'heures");

        MatriculeEnseignant7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculeEnseignant7ActionPerformed(evt);
            }
        });

        prenomEnseignant7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomEnseignant7ActionPerformed(evt);
            }
        });

        jLabel19.setText("Matricule Enseignant");

        javax.swing.GroupLayout ajoute_Enseignant1Layout = new javax.swing.GroupLayout(ajoute_Enseignant1);
        ajoute_Enseignant1.setLayout(ajoute_Enseignant1Layout);
        ajoute_Enseignant1Layout.setHorizontalGroup(
            ajoute_Enseignant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoute_Enseignant1Layout.createSequentialGroup()
                .addGroup(ajoute_Enseignant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoute_Enseignant1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MatriculeEnseignant7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomEnseignant7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addGap(5, 5, 5)
                        .addComponent(prenomEnseignant7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajoute_Enseignant1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ajoute_Enseignant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomEnseignant8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ajouterEnseignant1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ajoute_Enseignant1Layout.setVerticalGroup(
            ajoute_Enseignant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoute_Enseignant1Layout.createSequentialGroup()
                .addGroup(ajoute_Enseignant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoute_Enseignant1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajoute_Enseignant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ajoute_Enseignant1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ajoute_Enseignant1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(ajoute_Enseignant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(MatriculeEnseignant7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nomEnseignant7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(prenomEnseignant7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(ajoute_Enseignant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomEnseignant8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ajouterEnseignant1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AjouteEtudiant3.setText("Ajoute Unite");
        AjouteEtudiant3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouteEtudiant3ActionPerformed(evt);
            }
        });

        supprimerEtudiant3.setText("Suprimer Unite");
        supprimerEtudiant3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerEtudiant3ActionPerformed(evt);
            }
        });

        jButton6.setText("reduire");

        jScrollPane7.setDoubleBuffered(true);

        tableEnseignant1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code Unite", "Libelle", "Nombre d'heures", "Matricule Enseignant"
            }
        ));
        jScrollPane8.setViewportView(tableEnseignant1);

        jScrollPane7.setViewportView(jScrollPane8);

        javax.swing.GroupLayout enseignant3Layout = new javax.swing.GroupLayout(enseignant3);
        enseignant3.setLayout(enseignant3Layout);
        enseignant3Layout.setHorizontalGroup(
            enseignant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enseignant3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enseignant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(enseignant3Layout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enseignant3Layout.createSequentialGroup()
                        .addComponent(AjouteEtudiant3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(supprimerEtudiant3)
                        .addGap(18, 18, 18)
                        .addComponent(MatriculeEnseignant5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)))
                .addGap(33, 33, 33))
        );
        enseignant3Layout.setVerticalGroup(
            enseignant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enseignant3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enseignant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjouteEtudiant3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supprimerEtudiant3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatriculeEnseignant5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        AjouteEtudiant4.setText("Ajoute les notes d'un etudiant");
        AjouteEtudiant4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouteEtudiant4ActionPerformed(evt);
            }
        });

        supprimerEtudiant4.setText("Suprimer");
        supprimerEtudiant4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerEtudiant4ActionPerformed(evt);
            }
        });

        jButton7.setText("reduire");

        tableEnseignant2.setBackground(new java.awt.Color(245, 245, 245));
        tableEnseignant2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matricule etudiant", "Code unité", "Note CC", "Note TP ", "Note Examen"
            }
        ));
        tableEnseignant2.setColumnSelectionAllowed(true);
        tableEnseignant2.getTableHeader().setReorderingAllowed(false);
        jScrollPane10.setViewportView(tableEnseignant2);
        tableEnseignant2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jScrollPane9.setViewportView(jScrollPane10);

        javax.swing.GroupLayout enseignant4Layout = new javax.swing.GroupLayout(enseignant4);
        enseignant4.setLayout(enseignant4Layout);
        enseignant4Layout.setHorizontalGroup(
            enseignant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enseignant4Layout.createSequentialGroup()
                .addGroup(enseignant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(enseignant4Layout.createSequentialGroup()
                        .addContainerGap(41, Short.MAX_VALUE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enseignant4Layout.createSequentialGroup()
                        .addComponent(AjouteEtudiant4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(supprimerEtudiant4)
                        .addGap(18, 18, 18)
                        .addComponent(MatriculeEnseignant8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)))
                .addGap(33, 33, 33))
        );
        enseignant4Layout.setVerticalGroup(
            enseignant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enseignant4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enseignant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjouteEtudiant4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supprimerEtudiant4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatriculeEnseignant8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        ajouterEtuUni.setBackground(new java.awt.Color(0, 153, 0));
        ajouterEtuUni.setForeground(new java.awt.Color(255, 255, 255));
        ajouterEtuUni.setText("Ajouter");
        ajouterEtuUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterEtuUniActionPerformed(evt);
            }
        });

        jLabel20.setText("Matricule Etudiant");

        jLabel21.setText("Code Unite");

        jLabel22.setText("Note CC");

        MatriculeEtudiantU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculeEtudiantUActionPerformed(evt);
            }
        });

        CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCActionPerformed(evt);
            }
        });

        EX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXActionPerformed(evt);
            }
        });

        jLabel23.setText("Note Examen");

        TP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPActionPerformed(evt);
            }
        });

        jLabel24.setText("Note TP");

        javax.swing.GroupLayout ajoute_EtudiantU2Layout = new javax.swing.GroupLayout(ajoute_EtudiantU2);
        ajoute_EtudiantU2.setLayout(ajoute_EtudiantU2Layout);
        ajoute_EtudiantU2Layout.setHorizontalGroup(
            ajoute_EtudiantU2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoute_EtudiantU2Layout.createSequentialGroup()
                .addGroup(ajoute_EtudiantU2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoute_EtudiantU2Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(ajouterEtuUni, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajoute_EtudiantU2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EX, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TP, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajoute_EtudiantU2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel20)
                        .addGap(13, 13, 13)
                        .addComponent(MatriculeEtudiantU, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CodeUniteE, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addGap(5, 5, 5)
                        .addComponent(CC, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ajoute_EtudiantU2Layout.setVerticalGroup(
            ajoute_EtudiantU2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoute_EtudiantU2Layout.createSequentialGroup()
                .addGroup(ajoute_EtudiantU2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoute_EtudiantU2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajoute_EtudiantU2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ajoute_EtudiantU2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ajoute_EtudiantU2Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(ajoute_EtudiantU2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(MatriculeEtudiantU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CodeUniteE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(ajoute_EtudiantU2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoute_EtudiantU2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(ajoute_EtudiantU2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ajoute_EtudiantU2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(ajoute_EtudiantU2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(ajouterEtuUni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(ajoute_Etudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(ajoute_Enseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enseignant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enseignant3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ajoute_Enseignant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ajoute_EtudiantU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enseignant4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(ajoute_Etudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(ajoute_Enseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(enseignant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(ajoute_Enseignant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(enseignant3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(ajoute_EtudiantU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(enseignant4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouteEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouteEtudiantActionPerformed

        if (val) {
            
        ajoute_Etudiant.setVisible(true);
        AjouteEtudiant.setText("Annuler");
        val=false;
        
        }
        else  { ajoute_Etudiant.setVisible(false);
            AjouteEtudiant.setText("Ajouter Etudiant");
        val=true;}
       
    }//GEN-LAST:event_AjouteEtudiantActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Etudiant et1 = new Etudiant(Integer.parseInt(MatriculeEtudiant.getText()),nomEtudiant.getText(),prenomEtudiant.getText(), dateDeNaissanceEtudiant.getDate(),adresseEtudiant.getText());
        et1.insererEtudiant();
        try {
            affiche();
        } catch (SQLException ex) {
            Logger.getLogger(BDDAdminCeQuiVeut2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void prenomEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomEtudiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomEtudiantActionPerformed

    private void supprimerEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerEtudiantActionPerformed
        // TODO add your handling code here:
       
        Etudiant Etu_supp = new Etudiant (Integer.parseInt(MatriculeEtudiant1.getText()));
        Etu_supp.supprimerEtudiant();
        try {
            affiche();
        } catch (SQLException ex) {
            Logger.getLogger(BDDAdminCeQuiVeut2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_supprimerEtudiantActionPerformed

    private void adresseEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresseEtudiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresseEtudiantActionPerformed

    private void ChoisirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoisirActionPerformed
         String selectedValue = Choisir.getSelectedItem().toString();
        
    if (selectedValue.equals("Etudiant")) {
        
        ajoute_Etudiant.setVisible(false);
        ajoute_EtudiantU2.setVisible(false);
        enseignant4.setVisible(false);
        ajoute_Enseignant1.setVisible(false);
        enseignant3.setVisible(false);
        jPanel1.setVisible(true);
        ajoute_Enseignant.setVisible(false);
        enseignant2.setVisible(false);
        
    } else if (selectedValue.equals("Enseignant")) {
             try {
                 affiche2();
             } catch (SQLException ex) {
                 Logger.getLogger(BDDAdminCeQuiVeut2.class.getName()).log(Level.SEVERE, null, ex);
             }
        ajoute_Etudiant.setVisible(false);
        ajoute_EtudiantU2.setVisible(false);
        enseignant4.setVisible(false);
        ajoute_Enseignant1.setVisible(false);
        enseignant3.setVisible(false);
        jPanel1.setVisible(false);
        ajoute_Enseignant.setVisible(false); 
        enseignant2.setVisible(true);
    }else if (selectedValue.equals("Unite")) {
        
             try { 
                 afficheUnite();
             } catch (SQLException ex) {
                 Logger.getLogger(BDDAdminCeQuiVeut2.class.getName()).log(Level.SEVERE, null, ex);
             }
        ajoute_Etudiant.setVisible(false);
        ajoute_EtudiantU2.setVisible(false);
        enseignant4.setVisible(false);
        ajoute_Enseignant1.setVisible(!val2);
        enseignant3.setVisible(true);
        jPanel1.setVisible(false);
        ajoute_Enseignant.setVisible(false);
        enseignant2.setVisible(false);
        
    }else if (selectedValue.equals("EtudiantUnite")) {
        
        
        ajoute_Etudiant.setVisible(false);
        ajoute_EtudiantU2.setVisible(false);
        enseignant4.setVisible(true);
        ajoute_Enseignant1.setVisible(false);
        enseignant3.setVisible(false);
        jPanel1.setVisible(false);
        ajoute_Enseignant.setVisible(false);
        enseignant2.setVisible(false);
        
    }
    
    else {
         ajoute_Etudiant.setVisible(false);
        ajoute_EtudiantU2.setVisible(false);
        enseignant4.setVisible(false);
        ajoute_Enseignant1.setVisible(false);
        enseignant3.setVisible(false);
        jPanel1.setVisible(false);
        ajoute_Enseignant.setVisible(false);
        enseignant2.setVisible(false);
    }
    }//GEN-LAST:event_ChoisirActionPerformed

    private void AjouteEtudiant2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouteEtudiant2ActionPerformed
        // TODO add your handling code here:
        if (val1) {
        ajoute_Enseignant.setVisible(true);
        AjouteEtudiant2.setText("Annuler");
        val1=false;
        
        }
        else  { ajoute_Enseignant.setVisible(false);
            AjouteEtudiant2.setText("Ajouter Ensiegnant");
        val1=true;}
        
        
    }//GEN-LAST:event_AjouteEtudiant2ActionPerformed

    private void supprimerEtudiant2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerEtudiant2ActionPerformed
                        // TODO add your handling code here:
       
        Enseignant ens_supp = new Enseignant(Integer.parseInt(MatriculeEnseignant4.getText()));
        ens_supp.supprimerEnseignant();
        try {
            affiche2();
        } catch (SQLException ex) {
            Logger.getLogger(BDDAdminCeQuiVeut2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_supprimerEtudiant2ActionPerformed

    private void ajouterEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterEnseignantActionPerformed
            
        Enseignant es1 = new Enseignant(Integer.parseInt(MatriculeEnseignant6.getText()),nomEnseignant6.getText(),prenomEnseignant6.getText());
        es1.insererEnseignant();
        try {
            affiche2();
        } catch (SQLException ex) {
            Logger.getLogger(BDDAdminCeQuiVeut2.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_ajouterEnseignantActionPerformed

    private void prenomEnseignant6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomEnseignant6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomEnseignant6ActionPerformed

    private void MatriculeEnseignant6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculeEnseignant6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatriculeEnseignant6ActionPerformed

    private void ajouterEnseignant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterEnseignant1ActionPerformed
        // TODO add your handling code here:
        Unite unite = new Unite(MatriculeEnseignant7.getText(),nomEnseignant7.getText(),prenomEnseignant7.getText(), Integer.parseInt(nomEnseignant8.getText()));
        unite.insererUnite();
        try {
            afficheUnite();
        } catch (SQLException ex) {
            Logger.getLogger(BDDAdminCeQuiVeut2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ajouterEnseignant1ActionPerformed

    private void MatriculeEnseignant7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculeEnseignant7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatriculeEnseignant7ActionPerformed

    private void prenomEnseignant7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomEnseignant7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomEnseignant7ActionPerformed

    private void AjouteEtudiant3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouteEtudiant3ActionPerformed
        // TODO add your handling code here:
        if (val2) {
            
        ajoute_Enseignant1.setVisible(true);
        AjouteEtudiant3.setText("Annuler");
        val2=false;
        
        }
        else  { ajoute_Enseignant1.setVisible(false);
            AjouteEtudiant3.setText("Ajoute Unite");
        val2=true;}
        
    }//GEN-LAST:event_AjouteEtudiant3ActionPerformed

    private void supprimerEtudiant3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerEtudiant3ActionPerformed
        // TODO add your handling code here:
        Unite unite_supp = new Unite(MatriculeEnseignant5.getText());
        unite_supp.supprimerUnite();
        try {
            afficheUnite();
        } catch (SQLException ex) {
            Logger.getLogger(BDDAdminCeQuiVeut2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_supprimerEtudiant3ActionPerformed

    private void AjouteEtudiant4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouteEtudiant4ActionPerformed
         if (val2) {
            
        ajoute_EtudiantU2.setVisible(true);
        AjouteEtudiant4.setText("Annuler");
        val2=false;
        
        }
        else  { ajoute_EtudiantU2.setVisible(false);
            AjouteEtudiant4.setText("Ajoute les notes d'un etudiant");
        val2=true;} 
    }//GEN-LAST:event_AjouteEtudiant4ActionPerformed

    private void supprimerEtudiant4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerEtudiant4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supprimerEtudiant4ActionPerformed

    private void ajouterEtuUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterEtuUniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterEtuUniActionPerformed

    private void MatriculeEtudiantUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculeEtudiantUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatriculeEtudiantUActionPerformed

    private void CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCActionPerformed

    private void EXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXActionPerformed

    private void TPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TPActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(bool){
        jScrollPane2.setVisible(false);jButton3.setText("Affiche Tableau ");
                bool =false ;} else {jScrollPane2.setVisible(true);
                jButton3.setText("Réduire ");
                bool = true ; }
    }//GEN-LAST:event_jButton3ActionPerformed
    public void affiche() throws SQLException{
        
          
        DefaultTableModel tableModel = new DefaultTableModel();

        // Add columns to the table model
        tableModel.addColumn("Matricule");
        tableModel.addColumn("Nom");
        tableModel.addColumn("Prénom");
        tableModel.addColumn("Date De Naissance");
        tableModel.addColumn("Adresse");

        // Set the table model to the JTable
        jTable1.setModel(tableModel);
        
        // Create a list of data
        Etudiant etudiants =new Etudiant();
            // Add each element of the list as a new row to the table model

    // Ajouter chaque élément de la liste en tant que nouvelle ligne dans le modèle de table
    for (Etudiant rowData : etudiants.consultationEtudiants()) {
        tableModel.addRow(rowData.toVector());
    }
    jTable1.setModel(tableModel);

            jTable1.setModel(tableModel);
             
        
        jTable1.setVisible(true);
        
    }
        public void afficheUnite() throws SQLException{
        
          
         DefaultTableModel tableModel = new DefaultTableModel();

        // Add columns to the table model
        tableModel.addColumn("Code Unite");
        tableModel.addColumn("Libelle");
        tableModel.addColumn("Nombre Heures");
        tableModel.addColumn("Matricule Ensiegnant");

        // Set the table model to the JTable
        tableEnseignant1.setModel(tableModel);
        
        // Create a list of data
        Unite unites =new Unite ();
            // Add each element of the list as a new row to the table model

    // Ajouter chaque élément de la liste en tant que nouvelle ligne dans le modèle de table
    for (Unite rowData : unites.uniteConsultation()) {
        tableModel.addRow(rowData.toVector());
    }
    tableEnseignant1.setModel(tableModel);

            tableEnseignant1.setModel(tableModel);
        
        tableEnseignant1.setVisible(true);
        
    }
    
        public void affiche2() throws SQLException{
        
          
         DefaultTableModel tableModel = new DefaultTableModel();

        // Add columns to the table model
        tableModel.addColumn("Matricule");
        tableModel.addColumn("Nom");
        tableModel.addColumn("Prénom");

        // Set the table model to the JTable
        tableEnseignant.setModel(tableModel);
        
        // Create a list of data
        Enseignant enseignants =new Enseignant();
            // Add each element of the list as a new row to the table model

    // Ajouter chaque élément de la liste en tant que nouvelle ligne dans le modèle de table
    for (Enseignant rowData : enseignants.consultationEnseignants()) {
        tableModel.addRow(rowData.toVector());
    }
    tableEnseignant.setModel(tableModel);

            tableEnseignant.setModel(tableModel);
        
        tableEnseignant.setVisible(true);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void BDDFirstFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BDDAdminCeQuiVeut2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BDDAdminCeQuiVeut2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BDDAdminCeQuiVeut2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BDDAdminCeQuiVeut2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new BDDAdminCeQuiVeut2().setVisible(true);
                
                
            }
        });
    }
    public static void main(String[] args) {
        BDDFirstFrame();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouteEtudiant;
    private javax.swing.JButton AjouteEtudiant2;
    private javax.swing.JButton AjouteEtudiant3;
    private javax.swing.JButton AjouteEtudiant4;
    private javax.swing.JTextField CC;
    private javax.swing.JComboBox<String> Choisir;
    private javax.swing.JTextField CodeUniteE;
    private javax.swing.JTextField EX;
    private javax.swing.JTextField MatriculeEnseignant4;
    private javax.swing.JTextField MatriculeEnseignant5;
    private javax.swing.JTextField MatriculeEnseignant6;
    private javax.swing.JTextField MatriculeEnseignant7;
    private javax.swing.JTextField MatriculeEnseignant8;
    private javax.swing.JTextField MatriculeEtudiant;
    private javax.swing.JTextField MatriculeEtudiant1;
    private javax.swing.JTextField MatriculeEtudiantU;
    private javax.swing.JTextField TP;
    private javax.swing.JTextField adresseEtudiant;
    private javax.swing.JPanel ajoute_Enseignant;
    private javax.swing.JPanel ajoute_Enseignant1;
    private javax.swing.JPanel ajoute_Etudiant;
    private javax.swing.JPanel ajoute_EtudiantU2;
    private javax.swing.JButton ajouterEnseignant;
    private javax.swing.JButton ajouterEnseignant1;
    private javax.swing.JButton ajouterEtuUni;
    private com.toedter.calendar.JDateChooser dateDeNaissanceEtudiant;
    private javax.swing.JPanel enseignant2;
    private javax.swing.JPanel enseignant3;
    private javax.swing.JPanel enseignant4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JDialog jDialog6;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nomEnseignant6;
    private javax.swing.JTextField nomEnseignant7;
    private javax.swing.JTextField nomEnseignant8;
    private javax.swing.JTextField nomEtudiant;
    private javax.swing.JTextField prenomEnseignant6;
    private javax.swing.JTextField prenomEnseignant7;
    private javax.swing.JTextField prenomEtudiant;
    private javax.swing.JButton supprimerEtudiant;
    private javax.swing.JButton supprimerEtudiant2;
    private javax.swing.JButton supprimerEtudiant3;
    private javax.swing.JButton supprimerEtudiant4;
    private javax.swing.JTable tableEnseignant;
    private javax.swing.JTable tableEnseignant1;
    private javax.swing.JTable tableEnseignant2;
    // End of variables declaration//GEN-END:variables
}
