/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import java.sql.Date;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;


/**
 *
 * @author chemss
 */
public class ConsultationInsertionEns extends javax.swing.JFrame {
    private  CustomDialog dialog = new CustomDialog(this);
      
    /**
     * Creates new form ConsultationInsertionEns
     */
        
    public ConsultationInsertionEns() throws SQLException {
        initComponents();
        affiche3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jDialog4 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        enseignant2 = new javax.swing.JPanel();
        AjouteEnseignant2 = new javax.swing.JButton();
        MatriculeEtudiant122 = new javax.swing.JButton();
        MatriculeEnseignant13 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableEnseignant12 = new javax.swing.JTable();
        jFileChooser1 = new javax.swing.JFileChooser();
        ajoute_Enseignant = new javax.swing.JPanel();
        ajouterEnseignant12 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        MatriculeEnseignant12 = new javax.swing.JTextField();
        nomEnseignant12 = new javax.swing.JTextField();
        prenomEnseignant12 = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Enseignant");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        AjouteEnseignant2.setText("Ajoute Enseignant");
        AjouteEnseignant2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouteEnseignant2ActionPerformed(evt);
            }
        });

        MatriculeEtudiant122.setText("Matricule Enseignant");
        MatriculeEtudiant122.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculeEtudiant122ActionPerformed(evt);
            }
        });

        MatriculeEnseignant13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculeEnseignant13ActionPerformed(evt);
            }
        });

        jButton5.setText("reduire");

        tableEnseignant12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Matricule", "Nom", "Prenom"
            }
        ));
        jScrollPane6.setViewportView(tableEnseignant12);

        jScrollPane5.setViewportView(jScrollPane6);

        javax.swing.GroupLayout enseignant2Layout = new javax.swing.GroupLayout(enseignant2);
        enseignant2.setLayout(enseignant2Layout);
        enseignant2Layout.setHorizontalGroup(
            enseignant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enseignant2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enseignant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(enseignant2Layout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enseignant2Layout.createSequentialGroup()
                        .addComponent(AjouteEnseignant2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(MatriculeEtudiant122)
                        .addGap(18, 18, 18)
                        .addComponent(MatriculeEnseignant13, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addGap(33, 33, 33))
        );
        enseignant2Layout.setVerticalGroup(
            enseignant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enseignant2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enseignant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjouteEnseignant2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MatriculeEtudiant122, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatriculeEnseignant13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        ajouterEnseignant12.setBackground(new java.awt.Color(0, 153, 0));
        ajouterEnseignant12.setForeground(new java.awt.Color(255, 255, 255));
        ajouterEnseignant12.setText("Ajouter");
        ajouterEnseignant12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterEnseignant12ActionPerformed(evt);
            }
        });

        jLabel13.setText("Matricule");

        jLabel14.setText("Nom");

        jLabel15.setText("Prénom");

        MatriculeEnseignant12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculeEnseignant12ActionPerformed(evt);
            }
        });

        nomEnseignant12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomEnseignant12ActionPerformed(evt);
            }
        });

        prenomEnseignant12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomEnseignant12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajoute_EnseignantLayout = new javax.swing.GroupLayout(ajoute_Enseignant);
        ajoute_Enseignant.setLayout(ajoute_EnseignantLayout);
        ajoute_EnseignantLayout.setHorizontalGroup(
            ajoute_EnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoute_EnseignantLayout.createSequentialGroup()
                .addGroup(ajoute_EnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoute_EnseignantLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MatriculeEnseignant12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomEnseignant12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prenomEnseignant12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajoute_EnseignantLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(ajouterEnseignant12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ajoute_EnseignantLayout.setVerticalGroup(
            ajoute_EnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoute_EnseignantLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(ajoute_EnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoute_EnseignantLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13))
                    .addGroup(ajoute_EnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MatriculeEnseignant12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(nomEnseignant12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(prenomEnseignant12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ajouterEnseignant12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(ajoute_Enseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(enseignant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(ajoute_Enseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enseignant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prenomEnseignant12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomEnseignant12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomEnseignant12ActionPerformed

    private void MatriculeEnseignant12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculeEnseignant12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatriculeEnseignant12ActionPerformed

    private void ajouterEnseignant12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterEnseignant12ActionPerformed

        Enseignant es1 = new Enseignant(Integer.parseInt(MatriculeEnseignant12.getText()),nomEnseignant12.getText(),prenomEnseignant12.getText());
        es1.insererEnseignant();
        try {
            affiche3();
        } catch (SQLException ex1) {
            Logger.getLogger(BDDAdminCeQuiVeut2.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }//GEN-LAST:event_ajouterEnseignant12ActionPerformed

    private void MatriculeEtudiant122ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculeEtudiant122ActionPerformed
        // TODO add your handling code here:
        dialog.setVisible(true);
        Enseignant enseingant = new Enseignant(Integer.valueOf(MatriculeEnseignant13.getText()));
        try {
            Enseignant enseingantRech= enseingant.recherche();
            
        } 
         catch (NullPointerException ex) {
            dialog.setLabel("Etudiant n'existe pas");
            dialog.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ConsultationInsertionEns.class.getName()).log(Level.SEVERE, null, ex);
        }
        dialog.setLabel(new JLabel("Enseignant n'existe pas"));
    }//GEN-LAST:event_MatriculeEtudiant122ActionPerformed

    private void AjouteEnseignant2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouteEnseignant2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AjouteEnseignant2ActionPerformed

    private void nomEnseignant12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomEnseignant12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomEnseignant12ActionPerformed

    private void MatriculeEnseignant13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculeEnseignant13ActionPerformed
            
    }//GEN-LAST:event_MatriculeEnseignant13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void EnseignantFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultationInsertionEns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultationInsertionEns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultationInsertionEns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultationInsertionEns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ConsultationInsertionEns().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ConsultationInsertionEns.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    public static void main(String[] args) {
        EnseignantFrame();
    }
      
        public void affiche3() throws SQLException{
        
          
        DefaultTableModel tableModel = new DefaultTableModel();

        // Add columns to the table model
        tableModel.addColumn("Matricule");
        tableModel.addColumn("Nom");
        tableModel.addColumn("Prénom");

        // Set the table model to the JTable
        tableEnseignant12.setModel(tableModel);
        
        // Create a list of data
        Enseignant enseignants =new Enseignant();
            // Add each element of the list as a new row to the table model

    // Ajouter chaque élément de la liste en tant que nouvelle ligne dans le modèle de table
    for (Enseignant rowData : enseignants.consultationEnseignants()) {
        tableModel.addRow(rowData.toVector());
    }
    tableEnseignant12.setModel(tableModel);

            tableEnseignant12.setModel(tableModel);
        
        tableEnseignant12.setVisible(true);
        
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouteEnseignant2;
    private javax.swing.JTextField MatriculeEnseignant12;
    private javax.swing.JTextField MatriculeEnseignant13;
    private javax.swing.JButton MatriculeEtudiant122;
    private javax.swing.JPanel ajoute_Enseignant;
    private javax.swing.JButton ajouterEnseignant12;
    private javax.swing.JPanel enseignant2;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField nomEnseignant12;
    private javax.swing.JTextField prenomEnseignant12;
    private javax.swing.JTable tableEnseignant12;
    // End of variables declaration//GEN-END:variables
}
